name: PostMetastoreDeploy

trigger:
  branches:
    include:
      - devy

  paths:
    include:
      - '*'

variables:
  - ${{ if or(eq(variables['Build.SourceBranchName'], 'dev'), eq(variables['System.PullRequest.TargetBranchName'], 'dev')) }}:
    - group: vgdevadb360 
  - ${{ else }}: 
    - group: vgprdadb360


stages:
- stage: s_assignmetastore
  displayName: 'assign workspace to metastore'
  jobs:
  - job: j_assignmetastore
    displayName: 'job assign workspace to metastore'
  pool:
    name: jensazureagentpool
    steps:  
    # 1) Ensure Azure CLI is present
    - script: |
        set -euo pipefail
        if ! command -v az >/dev/null 2>&1; then
          echo "Azure CLI not found. Installing..."
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        else
          echo "Azure CLI already installed. Skipping."
        fi
      displayName: 'Check & install Azure CLI'

    - task: AzureCLI@2
      displayName: 'Attach workspace to metastore (account-scoped)'
      inputs:
        azureSubscription: 'ado-sc'
        scriptType: 'bash'
        scriptLocation: 'scriptPath'
        scriptPath: './iac-adb-360/helpers/attach-workspace-to-metastore.sh'
        arguments: '$(resourceGroupName) $(tenantId) $(clientId) $(clientSecret) $(metastorename)'
      env:
        DATABRICKS_ACCOUNT_ID: $(accountId)                 # the Databricks Account ID
        UC_REGION: westus2                                  # must match workspace region
        UC_STORAGE_ROOT: abfss://uc-root@<acct>.dfs.core.windows.net/

- stage: s_assignrepo
  displayName: 'assign repository to spn'
  jobs:
  - job: j_assignrepo
    displayName: 'Job assign repository to spn'
  pool:
    name: jensazureagentpool
    steps:
    - task: CmdLine@2
      displayName: 'Install Databricks CLI v2 (sudo)'
      inputs:
        script: |
          set -euo pipefail
          if command -v databricks >/dev/null 2>&1; then
            echo "Databricks CLI already present at: $(command -v databricks)"
            databricks version || true
            exit 0
          fi
          echo "Installing Databricks CLI..."
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh
          databricks version

    - task: AzureCLI@2
      displayName: 'Call script to assign workspace to repo'
      inputs:
        azureSubscription: 'adb-sc'
        scriptType: 'bash'
        scriptLocation: 'scriptPath'
        scriptPath: './iac-adb-360/helpers/attach-to-repo-github.sh'
        arguments: '$(resourceGroupName) $(tenantId) $(clientId) $(clientSecret) $(repourl) $(ghuser) $(ghpat)'


# - stage: s_createcluster
#   displayName: 'create the cluster'
#   jobs:
#   - job: j_createcluster
#     displayName: 'Job creating the cluster'
#     pool:
#       name: 'ubuntu-latest'
#     steps:
#     - task: CmdLine@2
#       inputs:
#         script: |
#           curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
#       displayName: 'Install Databricks CLI v 2'
#     - task: AzureCLI@2
#       displayName: 'Call script to create a cluster'
#       inputs:
#         azureSubscription: 'adb-sc'
#         scriptType: 'bash'
#         scriptLocation: 'scriptPath'
#         scriptPath: './iac-adb-360/helpers/create-cluster.sh'
#         arguments: '$(resourceGroupName) $(tenantId) $(clientId) $(clientSecret) $(clusterconf)'
