name: PostMetastoreCombinedDeploy

trigger:
  branches:
    include:
      - devy

  paths:
    include:
      - '*'

variables:
  - ${{ if or(eq(variables['Build.SourceBranchName'], 'dev'), eq(variables['System.PullRequest.TargetBranchName'], 'dev')) }}:
    - group: vgdevadb360
  - ${{ else }}:
    - group: vgprdadb360

pool:
  name: jensazureagentpool

stages:

- stage: s_assignrepo
  displayName: 'assign repository to spn'
  jobs:
  - job: j_assignrepo
    displayName: 'Job assign repository to spn'
    pool:
      name: jensazureagentpool
    steps:
      - script: |
          if ! command -v databricks &> /dev/null; then
            echo "Databricks CLI not found. Installing..."
            curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh
          else
            echo "Databricks CLI already installed. Skipping installation."
          fi
        displayName: 'Check and Install Databricks CLI'

      - script: |
          set -euo pipefail
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          
          if ! command -v az >/dev/null 2>&1; then
            echo "Azure CLI not found. Installing..."
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            az config set extension.dynamic_install_allow_preview=true
          else
            echo "Azure CLI already installed. Skipping."
          fi
        displayName: 'Check & install Azure CLI'

      - task: AzureCLI@2
        displayName: 'Call script to assign workspace to repo'
        inputs:
          azureSubscription: 'ado-sc'
          scriptType: 'bash'
          scriptLocation: 'scriptPath'
          scriptPath: './iac-adb-360/helpers/attach-to-repo-github.sh'
          arguments: '$(resourceGroupName) $(tenantId) $(clientId) $(clientSecret) $(repourl) $(ghuser) $(ghpat)'

- stage: s_createcatalogandschema
  displayName: 'create catalog and schema'
  jobs:
  - job: j_createcatalogandschema
    displayName: 'Job create catalog and schema'
    pool:
      name: jensazureagentpool
    steps:
      - task: AzureCLI@2
        displayName: 'Call script to create catalog and schema with its own storage loc'
        inputs:
          azureSubscription: 'ado-sc'
          scriptType: 'bash'
          scriptLocation: 'scriptPath'
          scriptPath: './iac-adb-360/helpers/create-ms-catalognschema-sepstor.sh'
          arguments: '$(resourceGroupName) $(tenantId) $(clientId) $(clientSecret) $(metastorename) $(env) $(catalogstorageaccountname) $(credname) $(accessconnectorid)'

      - task: AzureCLI@2
        displayName: 'Call script to create externallocation'
        inputs:
          azureSubscription: 'ado-sc'
          scriptType: 'bash'
          scriptLocation: 'scriptPath'
          scriptPath: './iac-adb-360/helpers/create-ms-externallocation.sh'
          arguments: '$(resourceGroupName) $(tenantId) $(clientId) $(clientSecret) $(metastorename) $(env) $(bronzestorageaccountname) $(credname) $(accessconnectorid)'
